name: Build & Test PR to main branch

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: echo "version=v$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ steps.get_version.outputs.version }}$"; then
            echo "Version ${{ steps.get_version.outputs.version }} already exists in this repo, please change package.json version before releasing"
            exit 1
          fi

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: lint
        run: bun lint:check

      - name: Test
        run: bun run test

      - name: Build Project
        run: bun run build
